# ------------------------------------------------------------------------------------------------
# --- Plot Gini coefficients for tract-term contributions (Plotting) ---
# ------------------------------------------------------------------------------------------------

# This script loads the Gini results data generated by tract_gini_coefficients.py and creates figures to visulize Lorenz curves, Gini coefficients, and tract visualizations. 

# ------------------------------------------------------------------------------------------------
# --- Load packages ---
# ------------------------------------------------------------------------------------------------

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
import pickle
import seaborn as sns
from pathlib import Path
project_root = Path(__file__).parent.parent.parent
sys.path.append(str(project_root))
from utils import tm_utils
from utils.tract_visualizer import TractVisualizer
from utils.figure_formatting import setup_figure, save_figure

# ------------------------------------------------------------------------------------------------
# --- Set up inputs and outputs ---
# ------------------------------------------------------------------------------------------------

# Set up directories
root_dir = '/Users/joelleba/PennLINC/tractmaps'
input_dir = os.path.join(root_dir, 'results/tract_functional_diversity/gini_coefficients')
output_dir = os.path.join(root_dir, 'results/tract_functional_diversity/gini_figures')

# create output directory if it doesn't exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Folder '{output_dir}' created.")
else:
    print(f"Folder '{output_dir}' already exists.")

# Set up colormap
_, _, _, _, _, bppy_cmap = tm_utils.make_colormaps()


# Define tracts to highlight in plots
highlighted_tracts = ['IFOF_left', 'VOF_left']

# ------------------------------------------------------------------------------------------------
# --- Load data ---
# ------------------------------------------------------------------------------------------------

print("Loading plotting data...")

# Load the plotting data from pickle
with open(os.path.join(input_dir, 'gini_plotting_data.pickle'), 'rb') as f:
    plotting_data = pickle.load(f)

# Extract data from pickle
all_tracts_data = plotting_data['all_tracts_data']
gini_results = plotting_data['gini_results']
gini_df = plotting_data['gini_df']
tract_name_mapping = plotting_data['tract_name_mapping']
tract_order = plotting_data['tract_order']
tract_order_full_names = plotting_data['tract_order_full_names']

print(f"Loaded data for {len(tract_order)} tracts")


# Load the abbreviations.xlsx file
abbreviations_path = os.path.join(root_dir, 'data/raw/tract_names/abbreviations.xlsx')
abbreviations_df = pd.read_excel(abbreviations_path)
# Remove "Segment" (case-insensitive), capitalize only first letter, preserve I/II/III
def format_pretty_name(name):
    import re
    # Remove "Segment" (case-insensitive, with optional spaces)
    name = re.sub(r'\s*[Ss]egment\s*', ' ', str(name)).strip()
    # Lowercase everything
    name = name.lower()
    # Capitalize first letter
    if len(name) > 0:
        name = name[0].upper() + name[1:]
    # Replace Roman numerals: use word boundaries to match 'i', 'ii', 'iii' as whole words
    name = re.sub(r'\bii\b', 'II', name, flags=re.IGNORECASE)
    name = re.sub(r'\biii\b', 'III', name, flags=re.IGNORECASE)
    name = re.sub(r'\bi\b', 'I', name, flags=re.IGNORECASE)
    return name

abbreviations_df['Pretty_Name'] = abbreviations_df['Full_Name'].apply(format_pretty_name)

# ------------------------------------------------------------------------------------------------
# --- Prepare data for plotting ---
# ------------------------------------------------------------------------------------------------

# Prepare data for plotting
tract_df = pd.DataFrame(all_tracts_data).T
tract_df.index.name = 'Tract'
all_terms = tract_df.reset_index().melt(id_vars='Tract', var_name='Term', value_name='Region-wise mean of normalized z-scores')
all_terms['Tract_Full'] = all_terms['Tract'].map(tract_name_mapping)
all_terms['Tract_Full'] = pd.Categorical(all_terms['Tract_Full'], categories=tract_order_full_names, ordered=True)

def get_hemisphere(tract):
    if tract.endswith('_left') or tract.endswith('_L'):
        return 'Left'
    elif tract.endswith('_right') or tract.endswith('_R'):
        return 'Right'
    else:
        return 'Unknown'

all_terms['Hemisphere'] = all_terms['Tract'].apply(get_hemisphere)
all_terms['Tract'] = pd.Categorical(all_terms['Tract'], categories=tract_order, ordered=True)

# Define colors for all plots
n_tracts = len(tract_order)
colors = [bppy_cmap(i / n_tracts) for i in range(n_tracts)]
tract_color_dict = dict(zip(tract_order, colors)) 

# add rgb_values column to gini_df
gini_df['rgb_values'] = gini_df['Tract'].map(tract_color_dict) # will need some editing in tract name column to make it work

# add the Pretty_Name column to gini_df  by merging with abbreviations_df
gini_df = gini_df.merge(abbreviations_df[['Tract', 'Pretty_Name']], on='Tract', how='left')

# ------------------------------------------------------------------------------------------------
# --- Lorenz curves for all tracts ---
# ------------------------------------------------------------------------------------------------

print("Creating Lorenz curves...")
fig, ax = setup_figure(width_mm=75, height_mm=60, margins_mm=(12, 2, 10, 2))
for i, tract in enumerate(tract_order):
    if tract not in gini_results:
        continue
    full_name = tract_name_mapping.get(tract, tract)
    
    # Highlight specific tracts
    if tract in highlighted_tracts: 
        ax.plot(gini_results[tract]["x_lorenz"], gini_results[tract]["y_lorenz"], 
                 color=tract_color_dict[tract], alpha=1.0, linewidth=1.5, label=full_name)
    else:
        ax.plot(gini_results[tract]["x_lorenz"], gini_results[tract]["y_lorenz"], 
                 color=tract_color_dict[tract], alpha=0.2, linewidth=0.3, label=full_name)

ax.plot([0, 1], [0, 1], color='grey', linestyle=':', linewidth=0.5, label='Equality')
sns.despine(ax=ax)
ax.set_xlabel('Cumulative proportion of terms')
ax.set_ylabel('Cumulative term contributions')
ax.spines['bottom'].set_linewidth(0.3)
ax.spines['left'].set_linewidth(0.3)
ax.tick_params(axis='both', width=0.3)
ax.legend().remove()
save_figure(fig, os.path.join(output_dir, 'lorenz_curves.svg'))
plt.close(fig)

# ------------------------------------------------------------------------------------------------
# --- Gini coefficients (sorted) ---
# ------------------------------------------------------------------------------------------------

print("Creating Gini coefficients plot...")
fig, ax = setup_figure(width_mm=80, height_mm=140, margins_mm=(52, 8, 8, 2))
for i, tract in enumerate(tract_order):
    y = gini_df[gini_df['Tract'] == tract]['Gini_Coefficient'].values[0]
    ax.scatter(y, n_tracts - 1 - i, color=tract_color_dict[tract], s=10)
ax.set_yticks(range(n_tracts))
ax.set_yticklabels(tract_order_full_names[::-1])
ax.set_ylabel('Tracts (sorted)')
ax.set_xlabel('Gini Coefficient')
sns.despine(ax=ax)
save_figure(fig, os.path.join(output_dir, 'gini_coefficients_sorted.svg'))
plt.close(fig)

# ------------------------------------------------------------------------------------------------
# --- Create separate plots for left and right hemispheres ---
# ------------------------------------------------------------------------------------------------

print("Creating separate hemisphere plots...")

# Separate tracts by hemisphere
left_tracts = [tract for tract in tract_order if tract.endswith('_left') or tract.endswith('_L')]
right_tracts = [tract for tract in tract_order if tract.endswith('_right') or tract.endswith('_R')]

# Left hemisphere plot
if left_tracts:
    fig, ax = setup_figure(width_mm=53, height_mm=75, margins_mm=(37, 4, 10, 0), base_pt=6)
    for i, tract in enumerate(left_tracts):
        y = gini_df[gini_df['Tract'] == tract]['Gini_Coefficient'].values[0]
        # Draw horizontal line from y-axis to point
        ax.plot([0, y], [len(left_tracts) - 1 - i, len(left_tracts) - 1 - i], 
                color=tract_color_dict[tract], linewidth=0.3, alpha=0.7)
        # Draw circle at the end
        ax.scatter(y, len(left_tracts) - 1 - i, color=tract_color_dict[tract], s=10, zorder=5)
    
    left_tract_names = [gini_df[gini_df['Tract'] == tract]['Pretty_Name'].values[0] for tract in left_tracts]
    ax.set_yticks(range(len(left_tracts)))
    ax.set_yticklabels(left_tract_names[::-1])
    ax.set_xlabel('Gini Coefficient')
    ax.set_xlim(0.4, 1.0)
    ax.set_xticks([0.4, 0.7, 1.0])
    ax.spines['bottom'].set_linewidth(0.3)
    ax.spines['left'].set_linewidth(0.3)
    ax.tick_params(axis='both', width=0.3)
    sns.despine(ax=ax)
    save_figure(fig, os.path.join(output_dir, 'gini_coefficients_left_hemisphere.svg'))
    plt.close(fig)

# Right hemisphere plot
if right_tracts:
    fig, ax = setup_figure(width_mm=53, height_mm=75, margins_mm=(37, 4, 10, 0), base_pt=6)
    for i, tract in enumerate(right_tracts):
        y = gini_df[gini_df['Tract'] == tract]['Gini_Coefficient'].values[0]
        # Draw horizontal line from y-axis to point
        ax.plot([0, y], [len(right_tracts) - 1 - i, len(right_tracts) - 1 - i], 
                color=tract_color_dict[tract], linewidth=0.3, alpha=0.7)
        # Draw circle at the end
        ax.scatter(y, len(right_tracts) - 1 - i, color=tract_color_dict[tract], s=10, zorder=5)
    
    right_tract_names = [gini_df[gini_df['Tract'] == tract]['Pretty_Name'].values[0] for tract in right_tracts]
    ax.set_yticks(range(len(right_tracts)))
    ax.set_yticklabels(right_tract_names[::-1])
    ax.set_xlabel('Gini Coefficient')
    ax.set_xlim(0.4, 1.0)
    ax.set_xticks([0.4, 0.7, 1.0])
    ax.spines['bottom'].set_linewidth(0.3)
    ax.spines['left'].set_linewidth(0.3)
    ax.tick_params(axis='both', width=0.3)
    sns.despine(ax=ax)
    save_figure(fig, os.path.join(output_dir, 'gini_coefficients_right_hemisphere.svg'))
    plt.close(fig)

print("Plots saved to: ", output_dir)

# ------------------------------------------------------------------------------------------------
# --- Visualize tracts in glass brain with Gini coefficients ---
# ------------------------------------------------------------------------------------------------

print("Creating tract visualizations...")
# Reload tract_visualizer to ensure we have the latest version
import importlib

# Import first, then reload
try:
    from utils.tract_visualizer import TractVisualizer
    importlib.reload(sys.modules['utils.tract_visualizer'])
    # Re-import after reload to get the updated class
    from utils.tract_visualizer import TractVisualizer
    print("Successfully reloaded tract_visualizer module")
except KeyError:
    # Module not loaded yet, just import normally
    from utils.tract_visualizer import TractVisualizer
    print("First import of tract_visualizer module")


# Create tract visualizations using TractVisualizer
output_dir = os.path.join(output_dir, 'tract_visualizations')
os.makedirs(output_dir, exist_ok=True)
viz = TractVisualizer(root_dir=root_dir,
                    output_dir=output_dir)

# Visualize all tracts sorted by Gini values (both medial and lateral views in 4x4 grid)
viz.visualize_tracts(gini_df, 
                    values_column='Gini_Coefficient', 
                    color_column='rgb_values', 
                    tract_name_column='Tract',
                    colorbar=False, 
                    plot_mode='all_tracts',
                    grid_orientation=None  # None creates both lateral and medial views automatically
                    )

# Alternative visualization: individual tracts sorted by Gini values
viz.visualize_tracts(gini_df, 
                    values_column='Gini_Coefficient', 
                    color_column='rgb_values', 
                    tract_name_column='Tract',
                    tract_list=['IFOF_left', 'AF_left', 'SLF_III_left', 'VOF_left', 'CST_left', 'F_left'],
                    tract_gradient_plot=True
                    )
