# ------------------------------------------------------------------------------------------------
# --- Plot Gini coefficients for tract-term contributions (Plotting) ---
# ------------------------------------------------------------------------------------------------

# This script loads the Gini results data generated by tract_gini_coefficients.py and creates figures to visulize Lorenz curves, Gini coefficients, and tract visualizations. 

# ------------------------------------------------------------------------------------------------
# --- Load packages ---
# ------------------------------------------------------------------------------------------------

import os
import pandas as pd
import matplotlib.pyplot as plt
import sys
import pickle
import seaborn as sns
from pathlib import Path
project_root = Path(__file__).parent.parent.parent
sys.path.append(str(project_root))
from utils import tm_utils
from utils.tract_visualizer import TractVisualizer

# ------------------------------------------------------------------------------------------------
# --- Set up inputs and outputs ---
# ------------------------------------------------------------------------------------------------

# Set up directories
root_dir = '/Users/joelleba/PennLINC/tractmaps'
input_dir = os.path.join(root_dir, 'results/tract_functional_diversity/gini_coefficients')
output_dir = os.path.join(root_dir, 'results/tract_functional_diversity/gini_figures')

# create output directory if it doesn't exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Folder '{output_dir}' created.")
else:
    print(f"Folder '{output_dir}' already exists.")

# Set up colormap
_, _, _, _, _, bppy_cmap = tm_utils.make_colormaps()

# set fontsize for all plots
plt.rcParams.update({'font.size': 18})

# Define tracts to highlight in plots
highlighted_tracts = ['IFOF_left', 'VOF_left']

# ------------------------------------------------------------------------------------------------
# --- Load data ---
# ------------------------------------------------------------------------------------------------

print("Loading plotting data...")

# Load the plotting data from pickle
with open(os.path.join(input_dir, 'gini_plotting_data.pickle'), 'rb') as f:
    plotting_data = pickle.load(f)

# Extract data from pickle
all_tracts_data = plotting_data['all_tracts_data']
gini_results = plotting_data['gini_results']
gini_df = plotting_data['gini_df']
tract_name_mapping = plotting_data['tract_name_mapping']
tract_order = plotting_data['tract_order']
tract_order_full_names = plotting_data['tract_order_full_names']

print(f"Loaded data for {len(tract_order)} tracts")


# Load the abbreviations.xlsx file
abbreviations_path = os.path.join(root_dir, 'data/raw/tract_names/abbreviations.xlsx')
abbreviations_df = pd.read_excel(abbreviations_path)
# capitalize only the first letter of each word, except when it's II or III
abbreviations_df['Pretty_Name'] = abbreviations_df['Full_Name'].str.title().str.replace('Ii', 'II').str.replace('Iii', 'III').str.replace('IIi', 'III')

# ------------------------------------------------------------------------------------------------
# --- Prepare data for plotting ---
# ------------------------------------------------------------------------------------------------

# Prepare data for plotting
tract_df = pd.DataFrame(all_tracts_data).T
tract_df.index.name = 'Tract'
all_terms = tract_df.reset_index().melt(id_vars='Tract', var_name='Term', value_name='Region-wise mean of normalized z-scores')
all_terms['Tract_Full'] = all_terms['Tract'].map(tract_name_mapping)
all_terms['Tract_Full'] = pd.Categorical(all_terms['Tract_Full'], categories=tract_order_full_names, ordered=True)

def get_hemisphere(tract):
    if tract.endswith('_left') or tract.endswith('_L'):
        return 'Left'
    elif tract.endswith('_right') or tract.endswith('_R'):
        return 'Right'
    else:
        return 'Unknown'

all_terms['Hemisphere'] = all_terms['Tract'].apply(get_hemisphere)
all_terms['Tract'] = pd.Categorical(all_terms['Tract'], categories=tract_order, ordered=True)

# Define colors for all plots
n_tracts = len(tract_order)
colors = [bppy_cmap(i / n_tracts) for i in range(n_tracts)]
tract_color_dict = dict(zip(tract_order, colors)) 

# add rgb_values column to gini_df
gini_df['rgb_values'] = gini_df['Tract'].map(tract_color_dict) # will need some editing in tract name column to make it work

# add the Pretty_Name column to gini_df  by merging with abbreviations_df
gini_df = gini_df.merge(abbreviations_df[['Tract', 'Pretty_Name']], on='Tract', how='left')

# ------------------------------------------------------------------------------------------------
# --- Lorenz curves for all tracts ---
# ------------------------------------------------------------------------------------------------

print("Creating Lorenz curves...")
plt.figure(figsize=(7, 6))
for i, tract in enumerate(tract_order):
    if tract not in gini_results:
        continue
    full_name = tract_name_mapping.get(tract, tract)
    
    # Highlight specific tracts
    if tract in highlighted_tracts: 
        plt.plot(gini_results[tract]["x_lorenz"], gini_results[tract]["y_lorenz"], 
                 color=tract_color_dict[tract], alpha=1.0, linewidth=3, label=full_name)
    else:
        plt.plot(gini_results[tract]["x_lorenz"], gini_results[tract]["y_lorenz"], 
                 color=tract_color_dict[tract], alpha=0.2, linewidth=0.5, label=full_name)

plt.plot([0, 1], [0, 1], color='grey', linestyle=':', lw=2, label='Equality')
sns.despine()
plt.xlabel('Cumulative Proportion of Terms')
plt.ylabel('Cumulative Term Contributions')
plt.legend().remove()
plt.tight_layout()
plt.savefig(os.path.join(output_dir, 'lorenz_curves.svg'), bbox_inches='tight')
plt.close()

# ------------------------------------------------------------------------------------------------
# --- Gini coefficients (sorted) ---
# ------------------------------------------------------------------------------------------------

print("Creating Gini coefficients plot...")
plt.figure(figsize=(8, 12))
for i, tract in enumerate(tract_order):
    y = gini_df[gini_df['Tract'] == tract]['Gini_Coefficient'].values[0]
    plt.scatter(y, n_tracts - 1 - i, color=tract_color_dict[tract], s=60)
plt.yticks(range(n_tracts), tract_order_full_names[::-1])
plt.ylabel('Tracts (sorted)')
plt.xlabel('Gini Coefficient')
sns.despine()
plt.tight_layout()
plt.savefig(os.path.join(output_dir, 'gini_coefficients_sorted.svg'))
plt.close()

# ------------------------------------------------------------------------------------------------
# --- Create separate plots for left and right hemispheres ---
# ------------------------------------------------------------------------------------------------

print("Creating separate hemisphere plots...")

# Separate tracts by hemisphere
left_tracts = [tract for tract in tract_order if tract.endswith('_left') or tract.endswith('_L')]
right_tracts = [tract for tract in tract_order if tract.endswith('_right') or tract.endswith('_R')]

# Left hemisphere plot
if left_tracts:
    plt.figure(figsize=(9, 10))
    for i, tract in enumerate(left_tracts):
        y = gini_df[gini_df['Tract'] == tract]['Gini_Coefficient'].values[0]
        # Draw horizontal line from y-axis to point
        plt.plot([0, y], [len(left_tracts) - 1 - i, len(left_tracts) - 1 - i], 
                color=tract_color_dict[tract], linewidth=2, alpha=0.7)
        # Draw circle at the end
        plt.scatter(y, len(left_tracts) - 1 - i, color=tract_color_dict[tract], s=80, zorder=5)
    
    left_tract_names = [gini_df[gini_df['Tract'] == tract]['Pretty_Name'].values[0] for tract in left_tracts]
    plt.yticks(range(len(left_tracts)), left_tract_names[::-1])
    plt.xlabel('Gini Coefficient')
    plt.xlim(0.4, 1.0)
    # plt.xticks([0.4, 0.6, 0.8, 1.0])
    sns.despine()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'gini_coefficients_left_hemisphere.svg'))
    plt.close()

# Right hemisphere plot
if right_tracts:
    plt.figure(figsize=(9, 10))
    for i, tract in enumerate(right_tracts):
        y = gini_df[gini_df['Tract'] == tract]['Gini_Coefficient'].values[0]
        # Draw horizontal line from y-axis to point
        plt.plot([0, y], [len(right_tracts) - 1 - i, len(right_tracts) - 1 - i], 
                color=tract_color_dict[tract], linewidth=2, alpha=0.7)
        # Draw circle at the end
        plt.scatter(y, len(right_tracts) - 1 - i, color=tract_color_dict[tract], s=80, zorder=5)
    
    right_tract_names = [gini_df[gini_df['Tract'] == tract]['Pretty_Name'].values[0] for tract in right_tracts]
    plt.yticks(range(len(right_tracts)), right_tract_names[::-1])
    plt.xlabel('Gini Coefficient')
    plt.xlim(0.4, 1.0)
    # plt.xticks([0.4, 0.6, 0.8, 1.0])
    sns.despine()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'gini_coefficients_right_hemisphere.svg'))
    plt.close()

print("Plots saved to: ", output_dir)

# ------------------------------------------------------------------------------------------------
# --- Visualize tracts in glass brain with Gini coefficients ---
# ------------------------------------------------------------------------------------------------

print("Creating tract visualizations...")
# Reload tract_visualizer to ensure we have the latest version
import importlib

# Import first, then reload
try:
    from utils.tract_visualizer import TractVisualizer
    importlib.reload(sys.modules['utils.tract_visualizer'])
    # Re-import after reload to get the updated class
    from utils.tract_visualizer import TractVisualizer
    print("Successfully reloaded tract_visualizer module")
except KeyError:
    # Module not loaded yet, just import normally
    from utils.tract_visualizer import TractVisualizer
    print("First import of tract_visualizer module")


# Create tract visualizations using TractVisualizer
output_dir = os.path.join(output_dir, 'tract_visualizations')
os.makedirs(output_dir, exist_ok=True)
viz = TractVisualizer(root_dir=root_dir,
                    output_dir=output_dir)

# Visualize all tracts sorted by Gini values
viz.visualize_tracts(gini_df, 
                    values_column='Gini_Coefficient', 
                    color_column='rgb_values', 
                    tract_name_column='Tract',
                    colorbar=True, 
                    plot_mode='all_tracts',
                    grid_orientation='vertical'
                    )

# Alternative visualization: individual tracts sorted by Gini values
viz.visualize_tracts(gini_df, 
                    values_column='Gini_Coefficient', 
                    color_column='rgb_values', 
                    tract_name_column='Tract',
                    tract_list=['IFOF_left', 'AF_left', 'SLF_III_left', 'VOF_left', 'CST_left', 'F_left'],
                    tract_gradient_plot=True
                    )
