# ------------------------------------------------------------------------------------------------
# --- Calculate Gini coefficients for tract functional diversity ---
# ------------------------------------------------------------------------------------------------

# This script loads the term contributions for each tract from tract_term_contributions.csv, generated by tract_term_contributions.py,
# and calculates Gini coefficients for each tract to assess functional diversity.
# The Gini coefficient measures inequality - higher values indicate more specialization (less diversity).

# ------------------------------------------------------------------------------------------------
# --- Load packages ---
# ------------------------------------------------------------------------------------------------

import os
import pandas as pd
import numpy as np
import pickle

# ------------------------------------------------------------------------------------------------
# --- Set up inputs and outputs ---
# ------------------------------------------------------------------------------------------------

# Set up directories
root_dir = '/Users/joelleba/PennLINC/tractmaps'

# input directory
decoding_results_dir = os.path.join(root_dir, 'results/tract_functional_decoding/decoding_results')

# output directory
gini_results_dir = os.path.join(root_dir, 'results/tract_functional_diversity/gini_coefficients')
if not os.path.exists(gini_results_dir):
    os.makedirs(gini_results_dir)
    print(f"Folder '{gini_results_dir}' created.")
else:
    print(f"Folder '{gini_results_dir}' already exists.")

# ------------------------------------------------------------------------------------------------
# --- Load data ---
# ------------------------------------------------------------------------------------------------

print("Loading term contributions data...")

# Load the pre-calculated term contributions
term_contrib_path = os.path.join(decoding_results_dir, 'tract_term_contributions.csv')
if not os.path.exists(term_contrib_path):
    raise FileNotFoundError(f"Term contributions file not found: {term_contrib_path}")
    print("Please run tract_term_contributions.py first to generate the required input data.")

term_contrib_df = pd.read_csv(term_contrib_path, index_col=0)
print(f"Loaded term contributions for {term_contrib_df.shape[1]} tracts and {term_contrib_df.shape[0]} terms")

# Load tract name mapping
tract_names_df = pd.read_excel(os.path.join(root_dir, 'data/raw/tract_names/abbreviations.xlsx'))
tract_name_mapping = dict(zip(tract_names_df['Tract'], tract_names_df['Tract_Long_Name']))

# ------------------------------------------------------------------------------------------------
# --- Function to calculate Gini coefficients for tracts ---
# ------------------------------------------------------------------------------------------------

def gini(values):
    """
    Compute Gini coefficient and prepare data for Lorenz curve.
    Args:
        values (np.array): Array of values for a tract.
    Returns:
        float: Gini coefficient.
        np.array: Cumulative population share for Lorenz curve (x-axis).
        np.array: Cumulative activation share for Lorenz curve (y-axis).
    """
    values = np.asarray(values).flatten()  # Flatten to 1D array
    values = np.sort(values)  # Sort values
    n = len(values)

    if n == 0 or np.sum(values) == 0:
        return 0, np.array([0]), np.array([0])  # Handle case with no values

    # Compute cumulative population and activation shares
    cumulative_population_share = np.arange(1, n + 1) / n
    cumulative_activation = np.cumsum(values)
    cumulative_activation_share = cumulative_activation / cumulative_activation[-1]

    # Calculate Gini coefficient
    gini_coeff = (2 * np.sum((np.arange(1, n + 1) * values)) / np.sum(values)) - (n + 1)
    gini_coeff = gini_coeff / n

    return gini_coeff, cumulative_population_share, cumulative_activation_share

def get_hemisphere(tract):
    """
    Determine hemisphere from tract name.
    Args:
        tract (str): Tract name
    Returns:
        str: Hemisphere ('Left', 'Right', or 'Unknown')
    """
    if tract.endswith('_left') or tract.endswith('_L'):
        return 'Left'
    elif tract.endswith('_right') or tract.endswith('_R'):
        return 'Right'
    else:
        return 'Unknown'

def calculate_tract_gini_coefficients(tract_term_contrib_data, tract_name_mapping=None):
    """
    Calculate Gini coefficients for tract functional diversity.
    
    Parameters:
    -----------
    tract_term_contrib_data : dict or pd.DataFrame
        Dictionary or DataFrame containing tract term contributions
        If DataFrame: tracts as columns, terms as rows
        If dict: tract names as keys, term contributions as values
    tract_name_mapping : dict, optional
        Mapping from short tract names to full names
    
    Returns:
    --------
    tuple: (gini_results, gini_df, gini_df_full_names, plotting_data)
        gini_results : dict
            Detailed results for each tract including Gini coefficient and Lorenz curve data
        gini_df : pd.DataFrame
            DataFrame with short tract names, Gini coefficients, and hemispheres
        gini_df_full_names : pd.DataFrame
            DataFrame with full tract names, Gini coefficients, and hemispheres (for CSV saving)
        plotting_data : dict
            All data needed for plotting, organized for easy access
    """
    
    print("Calculating Gini coefficients...")
    
    # Convert DataFrame to dictionary if necessary
    if isinstance(tract_term_contrib_data, pd.DataFrame):
        all_tracts_data = {}
        for tract in tract_term_contrib_data.columns:
            all_tracts_data[tract] = tract_term_contrib_data[tract]
    else:
        all_tracts_data = tract_term_contrib_data.copy()
    
    # Compute Gini for each tract based on their term contributions
    gini_results = {}
    for tract, term_contributions in all_tracts_data.items():
        gini_coeff, x_lorenz, y_lorenz = gini(term_contributions.values)
        gini_results[tract] = {
            "gini": gini_coeff,
            "x_lorenz": x_lorenz,
            "y_lorenz": y_lorenz,
            "activations": term_contributions.values
        }

    # Create df and sort by Gini coefficient
    gini_df = pd.DataFrame({
        'Tract': list(gini_results.keys()),
        'Gini_Coefficient': [gini_results[tract]["gini"] for tract in gini_results.keys()]
    })
    gini_df = gini_df.sort_values('Gini_Coefficient')
    gini_df['Hemisphere'] = gini_df['Tract'].apply(get_hemisphere)
    
    # Create df with full names for saving (like original code)
    gini_df_full_names = gini_df.copy()
    if tract_name_mapping:
        gini_df_full_names = gini_df_full_names.rename(columns={'Tract': 'Tract_Short_Name'})  # Rename original tract column
        gini_df_full_names['Tract'] = gini_df_full_names['Tract_Short_Name'].map(tract_name_mapping)  # Add long names as 'Tract'
    
    # Prepare plotting data
    plotting_data = {
        'all_tracts_data': all_tracts_data,
        'gini_results': gini_results,
        'gini_df': gini_df,  # Keep original short names for plotting
        'tract_name_mapping': tract_name_mapping,
        'tract_order': gini_df['Tract'].tolist(),  # Use short names like original
        'tract_order_full_names': [tract_name_mapping.get(tract, tract) for tract in gini_df['Tract'].tolist()] if tract_name_mapping else gini_df['Tract'].tolist()
    }
    
    print(f"Calculated Gini coefficients for {len(gini_results)} tracts")
    
    return gini_results, gini_df, gini_df_full_names, plotting_data

# ------------------------------------------------------------------------------------------------
# --- Calculate Gini coefficients ---
# ------------------------------------------------------------------------------------------------

gini_results, gini_df, gini_df_full_names, plotting_data = calculate_tract_gini_coefficients(term_contrib_df, tract_name_mapping)

# ------------------------------------------------------------------------------------------------
# --- Save Gini coefficients and data for plotting ---
# ------------------------------------------------------------------------------------------------

print("Saving Gini coefficients...")

# Save Gini coefficients with full names (generated by the function, like original code)
gini_df_full_names.to_csv(os.path.join(gini_results_dir, 'tract_gini_term_scores.csv'), index=False)
# TODO: fix the tract name mapping: short names don't seem to be added properly

# Save all data for plotting using pickle
with open(os.path.join(gini_results_dir, 'gini_plotting_data.pickle'), 'wb') as f:
    pickle.dump(plotting_data, f)

print(f"Saved Gini coefficients to: {os.path.join(gini_results_dir, 'tract_gini_term_scores.csv')}")
print(f"Saved plotting data to: {os.path.join(gini_results_dir, 'gini_plotting_data.pickle')}")
print("Gini coefficient calculation complete!")
