# -------------------------------------------------------------
# Plot Glasser region coordinates and Euclidean distances
# -------------------------------------------------------------
# Loads coordinates and precomputed Euclidean distances from
# data_prep/tract_euc_distance.py outputs and creates:
# - Region coordinates heatmap
# - Euclidean distance heatmaps with tract-specific overlays
# -------------------------------------------------------------


# ------------------------------------------------------------------------------------------------
# --- Load packages ---
# ------------------------------------------------------------------------------------------------

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sys
from pathlib import Path
project_root = Path(__file__).parent.parent.parent
sys.path.append(str(project_root))
from utils import tm_utils
from matplotlib.colors import ListedColormap
plt.switch_backend('Agg')

# ------------------------------------------------------------------------------------------------
# --- Set inputs and outputs ---
# ------------------------------------------------------------------------------------------------

# Paths
root = '/Users/joelleba/PennLINC/tractmaps'
deriv = f'{root}/data/derivatives'
results = f'{root}/results/spatial_embedding'

# Tracts to plot (left hemisphere)
tracts_for_maps = ['IFOF_left', 'VOF_left']

os.makedirs(results, exist_ok=True)

# Inputs generated by data_prep/tract_euc_distance.py
coords_csv = f'{deriv}/glasser_parcellation/glasser_coords.csv'
euc_npy = f'{deriv}/tracts/tracts_distances/euclidean_distances.npy'

# Load data
coords = pd.read_csv(coords_csv)
xyz = coords[['x-cog', 'y-cog', 'z-cog']].to_numpy()

# load euclidean distances
euclidean = np.load(euc_npy)
# select only first 100 regions
euclidean = euclidean[:180, :180]

# load tract probabilities
tracts_csv = f'{deriv}/tracts/tracts_probabilities/tracts_probabilities.csv'
tracts_df = pd.read_csv(tracts_csv)

# load tract pairwise distances
pairwise_csv = f"{deriv}/tracts/tracts_distances/tract_euclidean_distances_pairwise.csv"

# -------------------------------------------------------------
# Plot region XYZ coordinates
# -------------------------------------------------------------

# Get custom colormap
warm_cmap, tract_cmap, categ_warm, cool_warm_cmap, categ_cool_warm, bppy_cmap = tm_utils.make_colormaps()

# Build a 256-length reversed ListedColormap to satisfy tm_utils expectations
fds_base = bppy_cmap.reversed()
colors = np.vstack([np.array(fds_base(i)[:3]) for i in np.linspace(0, 1, 256)])
bppy_cmap = ListedColormap(colors)

# show the regions x coordinates matrix
regions_coords = coords[['x-cog', 'y-cog', 'z-cog']].to_numpy()

# select the first 6 rows
regions_coords = regions_coords[:6, :]

plt.figure(figsize=(3.5, 2.8), dpi=300)
sns.heatmap(
    regions_coords,
    annot=False,
    cmap=cool_warm_cmap,
    linecolor='white', linewidths=2,
    square=True,
    xticklabels=False, yticklabels=False,
    cbar=False,
)
plt.tight_layout()
plt.savefig(f"{results}/region_xyz_coords.svg", bbox_inches='tight', dpi=300)
plt.close()
print(f"Saved: {results}/region_xyz_coords.svg")

# -------------------------------------------------------------
# Plot Euclidean distances matrix
# -------------------------------------------------------------

# Render full matrix; avoid heavy white grid covering cells
plt.figure(figsize=(4, 4), dpi=300)
sns.heatmap(
    euclidean,
    annot=False,
    cmap=cool_warm_cmap,
    linecolor=None, linewidths=0,
    square=True,
    xticklabels=False, yticklabels=False,
    cbar=False,
)
plt.tight_layout()
plt.savefig(f"{results}/region_euclidean_distances.svg", bbox_inches='tight', dpi=300)
plt.close()
print(f"Saved: {results}/region_euclidean_distances.svg")

# ------------------------------------------------------------------------------------------------
# Create Euclidean distance colorbar
# ------------------------------------------------------------------------------------------------

fig_cbar, ax_cbar = plt.subplots(figsize=(8, 0.6), dpi=300)
sm = plt.cm.ScalarMappable(cmap=cool_warm_cmap)
sm.set_clim(np.nanmin(euclidean), np.nanmax(euclidean))
sm.set_array([])
cbar = fig_cbar.colorbar(sm, cax=ax_cbar, orientation='horizontal')
cbar.set_label('Euclidean distance (mm)', labelpad=8, fontsize=18)
cbar.ax.tick_params(labelsize=18)
cbar.outline.set_visible(False)
plt.tight_layout()

out_cbar = f"{results}/euclidean_distance_colorbar.svg"
plt.savefig(out_cbar, bbox_inches='tight', dpi=300)
plt.close()
print(f"Saved: {out_cbar}")

# ------------------------------------------------------------------------------------------------
# Upper-triangle Euclidean distances for regions connected to selected tracts
# ------------------------------------------------------------------------------------------------

# Connectivity threshold
conn_thresh = 0.5

n_regions = euclidean.shape[0]
# Mask to hide lower triangle and diagonal; keep only upper triangle without diagonal
upper_mask = np.triu(np.ones((n_regions, n_regions), dtype=bool), k=1)
lower_mask = ~upper_mask

for tract in tracts_for_maps:
    # tract connectivity boolean per region
    connected = (tracts_df[tract].values >= conn_thresh)
    # Build 2D subset mask for pairs where both endpoints are connected (and in the upper triangle)
    ii, jj = np.meshgrid(np.arange(n_regions), np.arange(n_regions), indexing='ij')
    subset_mask = upper_mask & (connected[ii] & connected[jj])
    print(f"Number of regions connected to {tract}: {np.sum(connected)}")

    plt.figure(figsize=(5.0, 5.0), dpi=300)
    ax = plt.gca()
    # Base layer: all upper-triangle cells, low alpha
    sns.heatmap(
        euclidean,
        mask=lower_mask,
        cmap=cool_warm_cmap,
        vmin=np.nanmin(euclidean), vmax=np.nanmax(euclidean),
        square=True,
        xticklabels=False, yticklabels=False,
        cbar=False,
        linewidths=0,
        linecolor=None,
        ax=ax,
    )
    # Set low alpha for the base pcolormesh
    if ax.collections:
        ax.collections[-1].set_alpha(0.18)

    # Overlay layer: only tract-connected pairs in upper triangle, full alpha
    overlay_mask = ~subset_mask  # mask True = hide; so hide all not in subset
    sns.heatmap(
        euclidean,
        mask=overlay_mask,
        cmap=cool_warm_cmap,
        vmin=np.nanmin(euclidean), vmax=np.nanmax(euclidean),
        square=True,
        xticklabels=False, yticklabels=False,
        cbar=False,
        linewidths=0,
        linecolor=None,
        ax=ax,
    )
    # Ensure overlay fully opaque
    if ax.collections:
        ax.collections[-1].set_alpha(1.0)

    plt.tight_layout()
    out_path = f"{results}/region_euclidean_upper_{tract}.svg"
    plt.savefig(out_path, bbox_inches='tight', dpi=300)
    plt.close()
    print(f"Saved: {out_path}")





